# based on:
# https://stackoverflow.com/questions/73806448/can-github-actions-edit-parts-of-readme-md

name: Dynamic Template

on: create

jobs:
  update_templates:
    name: "Update Templates"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@v4
        with:
          ref: main

      # Runs a set of commands using the runners shell
      - name: Update README.md
        run: |
          sed -i 's/<reponame>/'${{ github.event.repository.name }}'/' README.md
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit -am "Repository name in readme"
          git push
